# AUTOGENERATED FROM:
#     'backend/app/db/queries/insert_countries.edgeql'
#     'backend/app/db/queries/insert_genres.edgeql'
#     'backend/app/db/queries/insert_media.edgeql'
#     'backend/app/db/queries/insert_providers.edgeql'
#     'backend/app/db/queries/insert_user.edgeql'
#     'backend/app/db/queries/select_countries.edgeql'
#     'backend/app/db/queries/select_countries_with_providers.edgeql'
#     'backend/app/db/queries/select_country_providers.edgeql'
#     'backend/app/db/queries/select_genres.edgeql'
#     'backend/app/db/queries/select_user.edgeql'
#     'backend/app/db/queries/select_user_custom_lists.edgeql'
#     'backend/app/db/queries/select_user_favorites.edgeql'
#     'backend/app/db/queries/select_user_providers.edgeql'
#     'backend/app/db/queries/select_user_watch_list.edgeql'
#     'backend/app/db/queries/update_country_providers.edgeql'
#     'backend/app/db/queries/update_custom_list_add.edgeql'
#     'backend/app/db/queries/update_custom_list_remove.edgeql'
#     'backend/app/db/queries/update_user_custom_lists_add.edgeql'
#     'backend/app/db/queries/update_user_custom_lists_remove.edgeql'
#     'backend/app/db/queries/update_user_favorites_add.edgeql'
#     'backend/app/db/queries/update_user_favorites_remove.edgeql'
#     'backend/app/db/queries/update_user_provider_add.edgeql'
#     'backend/app/db/queries/update_user_provider_remove.edgeql'
#     'backend/app/db/queries/update_user_watch_list_add.edgeql'
#     'backend/app/db/queries/update_user_watch_list_remove.edgeql'
# WITH:
#     $ edgedb-py -P 5656 --tls-security insecure --user edgedb --password secret --file app/db/queries/generated.py


from __future__ import annotations
import dataclasses
import edgedb
import typing
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass

        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class InsertCountriesResult(NoPydanticValidation):
    id: uuid.UUID


@dataclasses.dataclass
class InsertGenresResult(NoPydanticValidation):
    id: uuid.UUID


@dataclasses.dataclass
class InsertMediaResult(NoPydanticValidation):
    id: uuid.UUID


@dataclasses.dataclass
class InsertProvidersResult(NoPydanticValidation):
    id: uuid.UUID


@dataclasses.dataclass
class InsertUserResult(NoPydanticValidation):
    id: uuid.UUID


@dataclasses.dataclass
class SelectCountriesResult(NoPydanticValidation):
    id: uuid.UUID
    label: str
    value: str


@dataclasses.dataclass
class SelectCountryProvidersResult(NoPydanticValidation):
    id: uuid.UUID
    label: str
    value: str
    providers: list[SelectCountryProvidersResultProvidersItem]


@dataclasses.dataclass
class SelectCountryProvidersResultProvidersItem(NoPydanticValidation):
    id: uuid.UUID
    provider_id: int
    logo_path: str | None
    provider_name: str

    @typing.overload
    def __getitem__(self, key: typing.Literal["@display_priority"]) -> int | None: ...

    def __getitem__(self, key: str) -> typing.Any:
        raise NotImplementedError


@dataclasses.dataclass
class SelectGenresResult(NoPydanticValidation):
    id: uuid.UUID
    label: str
    value: str


@dataclasses.dataclass
class SelectUserCustomListsResult(NoPydanticValidation):
    id: uuid.UUID
    custom_lists: list[SelectUserResultCustomListsItem]


@dataclasses.dataclass
class SelectUserFavoritesResult(NoPydanticValidation):
    id: uuid.UUID
    favorites: list[SelectUserResultCustomListsItemMediaItem]


@dataclasses.dataclass
class SelectUserProvidersResult(NoPydanticValidation):
    id: uuid.UUID
    providers: list[SelectUserResultProvidersItem]


@dataclasses.dataclass
class SelectUserResult(NoPydanticValidation):
    id: uuid.UUID
    email: str
    name: str
    custom_lists: list[SelectUserResultCustomListsItem]
    favorites: list[SelectUserResultCustomListsItemMediaItem]
    watch_list: list[SelectUserResultCustomListsItemMediaItem]
    providers: list[SelectUserResultProvidersItem]


@dataclasses.dataclass
class SelectUserResultCustomListsItem(NoPydanticValidation):
    id: uuid.UUID
    name: str
    media: list[SelectUserResultCustomListsItemMediaItem]


@dataclasses.dataclass
class SelectUserResultCustomListsItemMediaItem(NoPydanticValidation):
    id: uuid.UUID
    streamchaser_id: str


@dataclasses.dataclass
class SelectUserResultProvidersItem(NoPydanticValidation):
    id: uuid.UUID
    provider_id: int
    logo_path: str | None
    provider_name: str


@dataclasses.dataclass
class SelectUserWatchListResult(NoPydanticValidation):
    id: uuid.UUID
    watch_list: list[SelectUserResultCustomListsItemMediaItem]


@dataclasses.dataclass
class UpdateCustomListAddResult(NoPydanticValidation):
    id: uuid.UUID


async def insert_countries(
    executor: edgedb.AsyncIOExecutor,
    *,
    data: str,
) -> list[InsertCountriesResult]:
    return await executor.query(
        """\
        with
          raw_data := <json>$data,
        for item in json_array_unpack(raw_data) union (
          insert Country { label := <str>item['label'], value := <str>item['value'] }
          unless conflict
        )\
        """,
        data=data,
    )


async def insert_genres(
    executor: edgedb.AsyncIOExecutor,
    *,
    data: str,
) -> list[InsertGenresResult]:
    return await executor.query(
        """\
        with
          raw_data := <json>$data,
        for item in json_array_unpack(raw_data) union (
          insert Genre { label := <str>item['label'], value := <str>item['value'] }
          unless conflict
        )\
        """,
        data=data,
    )


async def insert_media(
    executor: edgedb.AsyncIOExecutor,
    *,
    streamchaser_id: str,
) -> InsertMediaResult | None:
    return await executor.query_single(
        """\
        insert Media {
          streamchaser_id := <str>$streamchaser_id
        }
        unless conflict;\
        """,
        streamchaser_id=streamchaser_id,
    )


async def insert_providers(
    executor: edgedb.AsyncIOExecutor,
    *,
    data: str,
) -> list[InsertProvidersResult]:
    return await executor.query(
        """\
        with
          raw_data := <json>$data,
        for item in json_array_unpack(raw_data) union (
          insert Provider {
            logo_path := <str>item['logo_path'],
            provider_name := <str>item['provider_name'],
            provider_id := <int16>item['provider_id']
          }
          unless conflict
        )\
        """,
        data=data,
    )


async def insert_user(
    executor: edgedb.AsyncIOExecutor,
    *,
    email: str,
    name: str,
) -> InsertUserResult | None:
    return await executor.query_single(
        """\
        insert User {
          email := <str>$email,
          name := <str>$name
        }
        unless conflict;\
        """,
        email=email,
        name=name,
    )


async def select_countries(
    executor: edgedb.AsyncIOExecutor,
) -> list[SelectCountriesResult]:
    return await executor.query(
        """\
        select Country {
          id,
          label,
          value
        }\
        """,
    )


async def select_countries_with_providers(
    executor: edgedb.AsyncIOExecutor,
) -> list[SelectCountriesResult]:
    return await executor.query(
        """\
        select Country {
          id,
          label,
          value
        }
        filter exists(.providers)
        # We sort by label, but need to split because
        # of the unicode flag "🇩🇿 Algeria"
        order by str_split(.label, " ")[1]\
        """,
    )


async def select_country_providers(
    executor: edgedb.AsyncIOExecutor,
    *,
    country_code: str,
) -> list[SelectCountryProvidersResult]:
    return await executor.query(
        """\
        select Country {
          id,
          label,
          value,
          providers: {
            id,
            provider_id,
            logo_path,
            provider_name,
            @display_priority
          }
          order by @display_priority
        }
        filter .value = <str>$country_code\
        """,
        country_code=country_code,
    )


async def select_genres(
    executor: edgedb.AsyncIOExecutor,
) -> list[SelectGenresResult]:
    return await executor.query(
        """\
        select Genre {
          id,
          label,
          value
        }\
        """,
    )


async def select_user(
    executor: edgedb.AsyncIOExecutor,
    *,
    email: str,
) -> SelectUserResult | None:
    return await executor.query_single(
        """\
        select User {
          id,
          email,
          name,
          custom_lists: {
            id,
            name,
            media: {
              id,
              streamchaser_id
              }
            },
          favorites: {
            id,
            streamchaser_id
          },
          watch_list: {
            id,
            streamchaser_id
          },
          providers: {
            id,
            provider_id,
            logo_path,
            provider_name
          }
        }
        filter .email = <str>$email\
        """,
        email=email,
    )


async def select_user_custom_lists(
    executor: edgedb.AsyncIOExecutor,
    *,
    email: str,
) -> SelectUserCustomListsResult | None:
    return await executor.query_single(
        """\
        select User {
          id,
          custom_lists: {
            id,
            name,
            media: {
              id,
              streamchaser_id
            }
          }
        }
        filter .email = <str>$email;\
        """,
        email=email,
    )


async def select_user_favorites(
    executor: edgedb.AsyncIOExecutor,
    *,
    email: str,
) -> SelectUserFavoritesResult | None:
    return await executor.query_single(
        """\
        select User {
          favorites: {
            id,
            streamchaser_id
          }
        }
        filter .email = <str>$email\
        """,
        email=email,
    )


async def select_user_providers(
    executor: edgedb.AsyncIOExecutor,
    *,
    email: str,
) -> SelectUserProvidersResult | None:
    return await executor.query_single(
        """\
        select User {
          id,
          providers: {
            id,
            provider_id,
            logo_path,
            provider_name
          }
        }
        filter .email = <str>$email\
        """,
        email=email,
    )


async def select_user_watch_list(
    executor: edgedb.AsyncIOExecutor,
    *,
    email: str,
) -> SelectUserWatchListResult | None:
    return await executor.query_single(
        """\
        select User {
          watch_list: {
            id,
            streamchaser_id
          }
        }
        filter .email = <str>$email\
        """,
        email=email,
    )


async def update_country_providers(
    executor: edgedb.AsyncIOExecutor,
    *,
    providers: str,
    country_code: str,
) -> list[InsertCountriesResult]:
    return await executor.query(
        """\
        with
          providers := <json>$providers
        for provider in json_array_unpack(providers) union (
          update Country
          filter .value = <str>$country_code
          set {
            providers := (
              select detached Provider {
                @display_priority := <int16>provider["display_priority"]
              }
              filter .provider_id = <int16>provider["provider_id"]
            )
          }
        )\
        """,
        providers=providers,
        country_code=country_code,
    )


async def update_custom_list_add(
    executor: edgedb.AsyncIOExecutor,
    *,
    id: uuid.UUID,
    streamchaser_id: str,
) -> UpdateCustomListAddResult | None:
    return await executor.query_single(
        """\
        update CustomList
        filter .id = <uuid>$id
        set {
          media += (
            insert Media { streamchaser_id := <str>$streamchaser_id }
            unless conflict on .streamchaser_id
            else (
              select Media filter .streamchaser_id = <str>$streamchaser_id
            )
          )
        };\
        """,
        id=id,
        streamchaser_id=streamchaser_id,
    )


async def update_custom_list_remove(
    executor: edgedb.AsyncIOExecutor,
    *,
    id: uuid.UUID,
    streamchaser_id: str,
) -> UpdateCustomListAddResult | None:
    return await executor.query_single(
        """\
        update CustomList
        filter .id = <uuid>$id
        set {
          media -= (
            select Media filter .streamchaser_id = <str>$streamchaser_id
          )
        };\
        """,
        id=id,
        streamchaser_id=streamchaser_id,
    )


async def update_user_custom_lists_add(
    executor: edgedb.AsyncIOExecutor,
    *,
    email: str,
    list_name: str,
) -> InsertUserResult | None:
    return await executor.query_single(
        """\
        update User
        filter .email = <str>$email
        set {
           custom_lists += (
            insert CustomList { name := <str>$list_name }
          )
        };\
        """,
        email=email,
        list_name=list_name,
    )


async def update_user_custom_lists_remove(
    executor: edgedb.AsyncIOExecutor,
    *,
    email: str,
    id: uuid.UUID,
) -> InsertUserResult | None:
    return await executor.query_single(
        """\
        update User
        filter .email = <str>$email
        set {
          custom_lists -= (
            select CustomList filter .id = <uuid>$id
          )
        };\
        """,
        email=email,
        id=id,
    )


async def update_user_favorites_add(
    executor: edgedb.AsyncIOExecutor,
    *,
    email: str,
    streamchaser_id: str,
) -> InsertUserResult | None:
    return await executor.query_single(
        """\
        update User
        filter .email = <str>$email
        set {
          favorites += (
            insert Media { streamchaser_id := <str>$streamchaser_id }
            unless conflict on .streamchaser_id
            else (
              select Media filter .streamchaser_id = <str>$streamchaser_id
            )
          )
        };\
        """,
        email=email,
        streamchaser_id=streamchaser_id,
    )


async def update_user_favorites_remove(
    executor: edgedb.AsyncIOExecutor,
    *,
    email: str,
    streamchaser_id: str,
) -> InsertUserResult | None:
    return await executor.query_single(
        """\
        update User
        filter .email = <str>$email
        set {
          favorites -= (
            select Media filter .streamchaser_id = <str>$streamchaser_id
          )
        };\
        """,
        email=email,
        streamchaser_id=streamchaser_id,
    )


async def update_user_provider_add(
    executor: edgedb.AsyncIOExecutor,
    *,
    email: str,
    provider_id: int,
) -> InsertUserResult | None:
    return await executor.query_single(
        """\
        update User
        filter .email = <str>$email
        set {
          providers += (
            select Provider
            filter .provider_id = <int16>$provider_id
          )
        };\
        """,
        email=email,
        provider_id=provider_id,
    )


async def update_user_provider_remove(
    executor: edgedb.AsyncIOExecutor,
    *,
    email: str,
    provider_id: int,
) -> InsertUserResult | None:
    return await executor.query_single(
        """\
        update User
        filter .email = <str>$email
        set {
          providers -= (
            select Provider
            filter .provider_id = <int16>$provider_id
          )
        };\
        """,
        email=email,
        provider_id=provider_id,
    )


async def update_user_watch_list_add(
    executor: edgedb.AsyncIOExecutor,
    *,
    email: str,
    streamchaser_id: str,
) -> InsertUserResult | None:
    return await executor.query_single(
        """\
        update User
        filter .email = <str>$email
        set {
          watch_list += (
            insert Media { streamchaser_id := <str>$streamchaser_id }
            unless conflict on .streamchaser_id
            else (
              select Media filter .streamchaser_id = <str>$streamchaser_id
            )
          )
        };\
        """,
        email=email,
        streamchaser_id=streamchaser_id,
    )


async def update_user_watch_list_remove(
    executor: edgedb.AsyncIOExecutor,
    *,
    email: str,
    streamchaser_id: str,
) -> InsertUserResult | None:
    return await executor.query_single(
        """\
        update User
        filter .email = <str>$email
        set {
          watch_list -= (
            select Media filter .streamchaser_id = <str>$streamchaser_id
          )
        };\
        """,
        email=email,
        streamchaser_id=streamchaser_id,
    )
