# AUTOGENERATED FROM 'backend/app/db/queries/insert_user.edgeql' WITH:
#     $ edgedb-py -P 5656 --tls-security insecure --user edgedb --password secret
from __future__ import annotations

import dataclasses
import uuid

import edgedb


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass

        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class InsertUserResult(NoPydanticValidation):
    id: uuid.UUID


async def insert_user(
    executor: edgedb.AsyncIOExecutor,
    *,
    email: str,
    name: str,
) -> InsertUserResult | None:
    return await executor.query_single(
        """\
        insert User {
          email := <str>$email,
          name := <str>$name
        }
        unless conflict;\
        """,
        email=email,
        name=name,
    )
