# AUTOGENERATED FROM 'backend/app/db/queries/insert_media.edgeql' WITH:
#     $ edgedb-py -P 5656 --tls-security insecure --user edgedb --password secret
from __future__ import annotations

import dataclasses
import uuid

import edgedb


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass

        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class InsertMediaResult(NoPydanticValidation):
    id: uuid.UUID


async def insert_media(
    executor: edgedb.AsyncIOExecutor,
    *,
    title: str,
    streamchaser_id: str,
) -> InsertMediaResult | None:
    return await executor.query_single(
        """\
        insert Media {
          title := <str>$title,
          streamchaser_id := <str>$streamchaser_id
        }
        unless conflict;\
        """,
        title=title,
        streamchaser_id=streamchaser_id,
    )
