# AUTOGENERATED FROM 'backend/app/db/queries/select_user_watch_list.edgeql' WITH:
#     $ edgedb-py -P 5656 --tls-security insecure --user edgedb --password secret
from __future__ import annotations

import dataclasses
import uuid

import edgedb


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass

        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class SelectUserWatchListResult(NoPydanticValidation):
    id: uuid.UUID
    watch_list: list[SelectUserWatchListResultWatchListItem]


@dataclasses.dataclass
class SelectUserWatchListResultWatchListItem(NoPydanticValidation):
    id: uuid.UUID
    title: str
    streamchaser_id: str


async def select_user_watch_list(
    executor: edgedb.AsyncIOExecutor,
    *,
    email: str,
) -> SelectUserWatchListResult | None:
    return await executor.query_single(
        """\
        select User {
          watch_list: {
            id,
            title,
            streamchaser_id
          }
        }
        filter .email = <str>$email\
        """,
        email=email,
    )
