# AUTOGENERATED FROM 'backend/app/db/queries/update_user_watch_list_remove.edgeql' WITH:
#     $ edgedb-py -P 5656 --tls-security insecure --user edgedb --password secret
from __future__ import annotations

import dataclasses
import uuid

import edgedb


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass

        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class UpdateUserWatchListRemoveResult(NoPydanticValidation):
    id: uuid.UUID


async def update_user_watch_list_remove(
    executor: edgedb.AsyncIOExecutor,
    *,
    email: str,
    streamchaser_id: str,
) -> UpdateUserWatchListRemoveResult | None:
    return await executor.query_single(
        """\
        update User
        filter .email = <str>$email
        set {
          watch_list -= (
            select Media filter .streamchaser_id = <str>$streamchaser_id
          )
        };\
        """,
        email=email,
        streamchaser_id=streamchaser_id,
    )
