definitions:
  main.Country:
    properties:
      iso_3166_1:
        type: string
      name:
        type: string
    type: object
  main.Genre:
    properties:
      label:
        type: string
      value:
        type: string
    type: object
  main.Health:
    properties:
      data:
        type: string
    type: object
info:
  contact: {}
paths:
  /:
    get:
      consumes:
      - '*/*'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Health'
      summary: Show the status of server.
  /countries:
    get:
      consumes:
      - '*/*'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Country'
            type: array
      summary: Gets the countries used by TMDB
  /genres:
    get:
      consumes:
      - '*/*'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Genre'
            type: array
      summary: Gets the genres used by TMDB
swagger: "2.0"
