version: "3"

services:
  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    container_name: prometheus
    networks:
      - prometheus
      - traefik
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus-web.rule=Host(`prometheus.${HOST_NAME}`)"
      - "traefik.http.routers.prometheus-secured.rule=Host(`prometheus.${HOST_NAME}`)"
      - "traefik.http.routers.prometheus-secured.tls.certresolver=mytlschallenge"
      - "traefik.http.routers.prom-api.middlewares=prometheus-auth"
      - "traefik.http.middlewares.prometheus-auth.basicauth.users=prometheus:$$2y$$12$$KmNp57BG8MyGMTV2gR4NpOKAH08e3ZaByZ0Z1Yqk6qSqW4LFgh7Nm"
      - "traefik.docker.network=traefik"

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    restart: unless-stopped
    container_name: node_exporter
    command:
      - "--path.rootfs=/host"
    networks:
      - prometheus
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

  cadvisor:
    image: zcube/cadvisor
    restart: unless-stopped
    container_name: cadvisor
    privileged: true
    devices:
      - "/dev/kmsg"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - prometheus

  # Uncomment if you want to use Grafana locally
  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   privileged: true
  #   restart: unless-stopped
  #   networks:
  #     - prometheus
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=password
  #     - GF_SERVER_HTTP_PORT=4000
  #   ports:
  #     - 4000:4000
  #   volumes:
  #     - grafana-storage:/var/lib/grafana

  umami:
    image: docker.umami.dev/umami-software/umami:postgresql-latest
    restart: unless-stopped
    container_name: umami
    networks:
      - traefik
      - umami
    ports:
      - 9999:9999
    environment:
      DATABASE_URL: postgresql://umami:umami@umami-db:5432/umami
    depends_on:
      - umami-db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.umami-web.rule=Host(`umami.${HOST_NAME}`)"
      - "traefik.http.routers.umami-secured.rule=Host(`umami.${HOST_NAME}`)"
      - "traefik.http.routers.umami.tls=true"
      - "traefik.http.routers.umami-secured.tls.certresolver=mytlschallenge"
      - "traefik.docker.network=traefik"

  umami-db:
    image: postgres:12-alpine
    restart: always
    container_name: umami-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - ./sql/schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - umami-db-data:/var/lib/postgresql/data
    networks:
      - umami

networks:
  traefik:
    external: true
  prometheus:
    external: true
  umami:
    external: false

volumes:
  prometheus:
  umami-db-data:
  grafana-storage:
